version: '3.9'

# name the resulting compose project after the name of the instance
# this enables us to easily host multiple instances on a single machine
name: ${INSTANCE_NAME:-self-hosted-api-trader-game}

services:
  gameservice:
    build: .
    image: ${IMAGE_NAME}
    networks:
      - default
    ports:
      - 3000:3000
    environment:
      - INSTANCE_NAME=${INSTANCE_NAME}
      - DATABASE_HOST=database

  database:
    image: mongo:6
    command: --replSet rs0 # create a replica set to allow for things like transactions
    environment:
      MONGO_INITDB_DATABASE: nest
    restart: always
    networks:
      - default
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db

  # Initilize the replica set once the database is up
  mongoinit:
    image: mongo:6
    depends_on:
      - database
    networks:
      - default
    restart: 'no'
    entrypoint:
      ['bash', '-c', "mongosh --host database:27017 --eval 'rs.initiate()'"]

#  authserver:
#    image: oryd/kratos:v0.11
#    restart: always
#    networks:
#      - default

volumes:
  db-data:

networks:
  default:
