version: '3.9'

services:
  gameservice:
    build: .
    image: ${IMAGE_NAME}
    networks:
      - default
    environment:
      - INSTANCE_NAME=${INSTANCE_NAME}

  database:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    restart: always
    networks:
      - default
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db

  authserver:
    image: oryd/kratos:v0.11
    restart: always
    networks:
      - default

volumes:
  db-data:

networks:
  default:
