version: '3.9'

services:
  gameservice:
    build: .
    image: ${IMAGE_NAME}
    networks:
      - default
    environment:
      - INSTANCE_NAME=${INSTANCE_NAME}
      - DATABASE_HOST=database

  database:
    image: mongo:6
    command:  --replSet rs0 # create a replica set to allow for things like transactions
    environment:
      MONGO_INITDB_DATABASE: nest
    restart: always
    networks:
      - default
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db

  # Initilize the replica set once the database is up
  mongoinit:
    image: mongo:6
    depends_on:
      - database
    restart: "no"
    entrypoint: [ "bash", "-c", "mongosh --host database:27017 --eval 'rs.initiate()'"]
 

#  authserver:
#    image: oryd/kratos:v0.11
#    restart: always
#    networks:
#      - default

volumes:
  db-data:

networks:
  default:
